---
tasks:
  - name: test-host-docker-executor-passoff-pt-one
    description: test the host to docker to host executor works
    type: command
    location:
      type: path
      at: pt1.sh
    execution_needs:
      - name: host
    internal: true
  - name: test-host-docker-executor-passoff-pt-two
    description: test the host to docker to host executor works
    type: command
    location:
      type: path
      at: pt2.sh
    execution_needs:
      - name: docker
    internal: true
  - name: test-host-docker-executor-passoff-pt-three
    description: test the host to docker to host executor works
    location:
      type: path
      at: pt3.sh
    execution_needs:
      - name: host
    internal: true
  - name: host-docker-passoff-pipeline
    description: run all the host-docker-host passoff tasks
    type: pipeline
    steps:
      - name: pt-one
        task: test-host-docker-executor-passoff-pt-one
      - name: pt-two
        task: test-host-docker-executor-passoff-pt-two
      - name: pt-three
        task: test-host-docker-executor-passoff-pt-three
    internal: true
