---
trigger:
  branches:
    include:
    - 'master'

pr: none

pool:
  vmImage: 'ubuntu-18.04'

variables: []

steps:
  - task: DockerInstaller@0
    displayName: Docker Installer
    inputs:
      releaseType: stable

  - script: |
      mkdir -p ./scratch/
      (cd ./scratch/ && curl -sSL -o dl https://github.com/SecurityInsanity/dev-loop/releases/download/0.1.1/dl-linux && chmod +x dl)
    displayName: Download Dev-Loop

  - script: |
      ./scratch/dl exec build dl-release
    displayName: Build Dev-Loop Release
  - script: |
      cd ./e2e/
      DL_COMMAND="../target/dl-release" ./run-all-tests.sh
    displayName: Validate Dev-Loop Release

  - task: PublishPipelineArtifact@1
    inputs:
      path: $(System.DefaultWorkingDirectory)/target/dl-release
      artifact: dl-linux
    displayName: Publish Dev-Loop Release
