---
trigger:
  branches:
    include:
    - 'trunk'

pr: none

pool:
  vmImage: 'macos-10.14'

variables: []

steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install Rust
  - script: |
      brew install openssl
    displayName: Install OpenSSL

  - script: |
      mkdir -p ./scratch/
      (cd ./scratch/ && curl -sSL -o dl https://dev-loop-builds.sfo2.digitaloceanspaces.com/latest/dl-osx && chmod +x dl)
    displayName: Download Dev-Loop

  - script: |
      ./scratch/dl exec ci-only build-osx-dl-release
    displayName: Build Dev-Loop Release OSX

  - task: PublishPipelineArtifact@1
    inputs:
      path: $(System.DefaultWorkingDirectory)/target/dl-osx-release
      artifact: dl-osx
    displayName: Publish Dev-Loop Release

  - script: |
      brew install s3cmd
      ./target/dl-osx-release exec ci-only upload-to-spaces-osx
    displayName: Publish to Digital Ocean Spaces
    env:
      DL_SPACES_BUILD_KEY: $(DL_SPACES_BUILD_KEY)
      DL_SPACES_BUILD_SECRET: $(DL_SPACES_BUILD_SECRET)