---
trigger: none

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-18.04'

variables: []

steps:
  - task: DockerInstaller@0
    displayName: Docker Installer
    inputs:
      releaseType: stable

  - script: |
      mkdir -p ./scratch/
      (cd ./scratch/ && curl -sSL -o dl https://dev-loop-builds.sfo2.digitaloceanspaces.com/latest/dl-linux && chmod +x dl)
    displayName: Download Dev-Loop

  - script: |
      ./scratch/dl exec lint
    displayName: Lint Dev-Loop
  - script: |
      ./scratch/dl exec test
    displayName: Test Dev-Loop
  - script: |
      ./scratch/dl exec build dl-release
    displayName: Build Dev-Loop Release
  - script: |
      cd ./e2e/linux-e2e/
      DL_COMMAND="../../target/dl-release" ./run-all-tests.sh
    displayName: Validate Dev-Loop Release
