---
name: Linux Merged

on:
  push:
    branches:
      - trunk

jobs:
  build_validate_release:
    name: Build and Validate and Publish Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Dev-Loop
        run: mkdir -p ./scratch/ && (cd ./scratch/ && curl -sSL -o dl https://dev-loop-builds.sfo2.digitaloceanspaces.com/latest/dl-linux && chmod +x dl)

      - name: Build Release
        run: ./scratch/dl exec build dl-release
      - name: Validate Release
        run: (cd ./e2e/linux-e2e/ && DL_COMMAND="../../target/dl-release" ./run-all-tests.sh)
      - name: Publish
        run: sudo apt-get update && sudo apt-get -y install s3cmd && ./target/dl-release exec ci-only upload-to-spaces-linux
        env:
          DL_SPACES_BUILD_KEY: ${{ secrets.DL_SPACES_BUILD_KEY }}
          DL_SPACES_BUILD_SECRET: ${{ secrets.DL_SPACES_BUILD_SECRET }}